# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAH-mpwB7g3MnqYU-ooUBF1t99RP27dZ9addtMVXD";
    path = fetchzip {
      url = "https://www.sqlite.org/2025/sqlite-amalgamation-3490200.zip";
      hash = "sha256-zw9D86WTkqQlZIKcu2z808+4mc11bqct4GLnQsavDRw=";
    };
  }
  {
    name = "cli-0.10.0-2eKe_5kEAQBeHqKxUHNTGnETzu81rqKWwT1WPt1jXBt0";
    path = fetchgit {
      url = "https://github.com/sam701/zig-cli";
      rev = "cb44aade25a3c1eddd8b6f990b50c2189442c1e2";
      hash = "sha256-/rmfwWseEeqK7nDdSHKwOAPmdsBpFD9/1wg1uHLJ+eU=";
    };
  }
  {
    name = "sqlite-3.48.0-F2R_a8eODgD9X8XjvWlZ1K7C-tDuHae4FuShM2N-yIT2";
    path = fetchgit {
      url = "https://github.com/vrischmann/zig-sqlite";
      rev = "0b75ba276d34de3141ec1697e3ef7c836d7b38e7";
      hash = "sha256-p52EfIeMpbtkgAOGPjtHSt64FmZABjCZijaZglUPEPQ=";
    };
  }
]
